### ISSUE TITLE
Doesn't support above angular version 11 without use of force

### ISSUE THREAD

**Issue by Sam-Davis** [dineeek/ngx-google-translate-ui#2]
@angular/common@"^14.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^11.1.2" from ngx-google-translate-ui@1.2.0
npm ERR! node_modules/ngx-google-translate-ui
npm ERR!   ngx-google-translate-ui@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps

**Comment by dineeek** [comment]
Version 2.0.0 now supports up to Angular v15.
